---
# configure the postgresql database and roles
# https://stackoverflow.com/questions/45457694/ansible-postgresql-module-to-create-role-and-add-database
# https://blog.apcelent.com/using-ansible-to-set-up-postgresql.html
- name: Install Postgres
  apt:
    name: "{{ postgres_core }}"
    force_apt_get: True
    update_cache: yes
    state: present

- name: Ensure the Postgres service is running
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Create the "{{ postgres_database }}" db
  postgresql_db:
    name: "{{ postgres_database }}"
    template: "template0"
    encoding: UTF8
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
    state: present
  become_user: postgres

- name: Ensure user has access to the database
  postgresql_user:
    db: "{{ postgres_database }}"
    name: "{{ postgres_user }}"
    password: "{{ postgres_password }}"
    priv: ALL
    state: present
  become_user: postgres

- name: Ensure user does not have unnecessary privileges
  postgresql_user:
    name: "{{ postgres_user }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB
    state: present
  become_user: postgres
