---
  # fetch source code and install
- name: Clone source repository
  git:
    repo: "{{ repo_url }}"
    dest: /home/{{ ansible_ssh_user }}/{{ app_name }}
    version: master   # SHA-1 hash, the literal string HEAD, a branch name, or a tag name
    update: yes  # Does a git pull if the repo already exists
    force: yes

- name: Install virtualenv packages
  pip:
    requirements: /home/{{ ansible_ssh_user }}/{{ app_name }}/requirements.txt
    virtualenv: /home/{{ ansible_ssh_user }}/{{ app_name }}/env
    virtualenv_python: python3

- name: Install {{ app_name }} source
  pip:
    name: /home/{{ ansible_ssh_user }}/{{ app_name }}
    extra_args: '-e'   # installs editably
    virtualenv: /home/{{ ansible_ssh_user }}/{{ app_name }}/env
