---
- name: Running Terminate plays
  debug:
    msg: "Terminating specified instance"

- name: Initialize list var
  set_fact:
    instance_ids: []

# # elastic IP dissociation
# - name: Dissociate and release EIPs associated with instances
#   ec2_eip:
#     state: absent
#     region: "{{ region }}"
#     device_id: "{{ hostvars[item].ec2_id }}"
#     release_on_disassociation: True
#   with_items: "{{ host_name[webserver] }}"

- name: Gather facts for running instances
  ec2_instance_facts:
    region: "{{ region }}"
    filters:
      instance-state-name: ["running"]
      "tag:Name": "{{ Name }}"
  register: ec2_metadata

- name: Add instance_id to list
  no_log: True
  set_fact:
    instance_ids: "{{ instance_ids }} + [ '{{ item.instance_id }}' ] "
  with_items: "{{ ec2_metadata.instances }}"

- name: Terminate instances
  ec2:
    region: "{{ region }}"
    state: 'absent'
    instance_ids: "{{ item }}"
  with_items: "{{ instance_ids }}"
